2019-03-29 23:27:08,082-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:27:08,082-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:27:08,082-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:27:08,084-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:27:08,084-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:27:08,085-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:27:08,085-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:27:08,086-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:27:08,086-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:27:08,086-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:27:08,086-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:27:08,087-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:27:08,087-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:27:08,087-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:27:08,088-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:27:08,088-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:27:08,089-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:27:08,089-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:27:08,089-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:27:08,089-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:30:30,676-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:30:30,676-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:30:30,677-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:30:30,678-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:30:30,679-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:30:30,679-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:30:30,680-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:30:30,680-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:30:30,681-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:30:30,681-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:30:30,681-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:30:30,682-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:30:30,682-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:30:30,683-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:30:30,683-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:30:30,683-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:30:30,684-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:30:30,684-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:30:30,684-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:30:30,685-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:04,128-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:04,128-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:34:04,128-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:34:04,129-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:04,170-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:04,171-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:34:04,171-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:34:04,172-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:04,177-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:04,177-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:34:04,177-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:34:04,178-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:04,183-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:04,183-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:34:04,184-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:34:04,184-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:04,190-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:04,190-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:34:04,190-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:34:04,191-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:12,184-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:12,185-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:34:12,185-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:34:12,187-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:12,187-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:12,187-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:34:12,188-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:34:12,188-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:12,189-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:12,189-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:34:12,189-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:34:12,190-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:12,190-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:12,190-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:34:12,190-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:34:12,191-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:34:12,191-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:34:12,191-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:34:12,192-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:34:12,192-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:35:13,953-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:35:13,953-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:35:13,953-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:35:13,955-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:35:13,956-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:35:13,956-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:35:13,956-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:35:13,957-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:35:13,957-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:35:13,957-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:35:13,957-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:35:13,958-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:35:13,958-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:35:13,959-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:35:13,959-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:35:13,959-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:35:13,960-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:35:13,960-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:35:13,960-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:35:13,960-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:51,944-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:51,944-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:36:51,945-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:36:52,039-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:52,040-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:36:52,040-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:52,056-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:52,056-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:36:52,057-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:36:52,146-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:52,147-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:36:52,147-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:52,148-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:52,148-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:36:52,148-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:36:52,231-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:52,231-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:36:52,232-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:52,232-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:52,232-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:36:52,233-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:36:52,316-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:52,316-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:36:52,316-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:52,317-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:52,317-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:36:52,317-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:36:52,405-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:52,405-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:36:52,406-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:57,827-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:57,827-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:36:57,827-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:36:57,922-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:57,922-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:36:57,922-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:57,923-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:57,924-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:36:57,924-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:36:58,008-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:58,008-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:36:58,009-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:58,009-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:58,010-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:36:58,010-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:36:58,093-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:58,093-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:36:58,094-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:58,094-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:58,094-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:36:58,095-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:36:58,177-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:58,178-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:36:58,178-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:36:58,178-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:36:58,179-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:36:58,179-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:36:58,265-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:36:58,265-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:36:58,265-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:37:50,379-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:37:50,379-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:37:50,379-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:37:50,472-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:37:50,472-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:37:50,502-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:37:50,502-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:37:50,502-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:37:50,503-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:37:50,591-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:37:50,592-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:37:50,620-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:37:50,621-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:37:50,621-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:37:50,621-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:37:50,704-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:37:50,704-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:37:50,732-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:37:50,732-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:37:50,732-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:37:50,732-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:37:50,817-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:37:50,817-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:37:50,845-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:37:50,846-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:37:50,846-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:37:50,846-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:37:50,935-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:37:50,936-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:37:50,963-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:38:47,560-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:38:47,561-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:38:47,561-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:38:47,650-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:38:47,666-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:38:47,719-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:38:47,720-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:38:47,720-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:38:47,808-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:38:47,822-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:38:47,823-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:38:47,823-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:38:47,824-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:38:47,911-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:38:47,912-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-29 23:38:47,931-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:38:47,932-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:38:47,932-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:38:47,932-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:38:48,013-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:38:48,014-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-29 23:38:48,028-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:38:48,029-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:38:48,029-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:38:48,029-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:38:48,114-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:38:48,114-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20111'
- 10001
+ 20111

2019-03-29 23:38:48,129-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:46,387-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:46,387-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:39:46,387-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:39:46,478-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:46,479-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:39:46,493-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:46,495-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:46,495-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:39:46,496-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:39:46,590-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:46,590-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:39:46,605-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:46,606-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:46,606-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:39:46,606-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:39:46,695-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:46,695-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:39:46,710-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:46,711-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:46,711-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:39:46,711-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:39:46,796-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:46,796-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:39:46,810-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:46,810-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:46,810-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:39:46,811-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:39:46,896-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:46,897-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:39:46,911-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:49,811-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:49,811-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:39:49,812-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:39:49,902-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:49,902-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:39:49,916-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:49,918-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:49,918-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:39:49,918-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:39:50,003-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:50,003-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:39:50,017-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:50,018-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:50,018-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:39:50,018-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:39:50,104-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:50,104-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:39:50,118-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:50,119-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:50,119-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:39:50,119-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:39:50,202-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:50,202-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:39:50,216-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:39:50,216-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:39:50,216-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:39:50,217-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:39:50,302-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:39:50,302-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:39:50,316-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:02,358-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:02,358-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:41:02,359-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:41:02,450-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:02,450-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:41:02,481-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:02,482-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:02,482-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:41:02,482-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:41:02,572-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:02,572-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '10001'
2019-03-29 23:41:02,600-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:02,601-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:02,601-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:41:02,601-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:41:02,687-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:02,688-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:41:02,716-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:02,717-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:02,717-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:41:02,717-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:41:02,799-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:02,799-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20103'
2019-03-29 23:41:02,826-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:02,826-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:02,826-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:41:02,827-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:41:02,909-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:02,909-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：10001 != '20111'
2019-03-29 23:41:02,936-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:16,355-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:16,356-INFO-api_logging.py-api_frame_work-日志信息:正在运行第1条用例：正常登陆
2019-03-29 23:41:16,356-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:41:16,445-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:16,474-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:16,475-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:16,475-INFO-api_logging.py-api_frame_work-日志信息:正在运行第2条用例：正常登陆
2019-03-29 23:41:16,475-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-29 23:41:16,563-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:16,591-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:16,591-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:16,591-INFO-api_logging.py-api_frame_work-日志信息:正在运行第3条用例：正常key
2019-03-29 23:41:16,591-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '', 'pwd': '123456'}
2019-03-29 23:41:16,672-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:16,673-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-29 23:41:16,701-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:16,702-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:16,703-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:41:16,703-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': '18688773467', 'pwd': ''}
2019-03-29 23:41:16,785-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:16,785-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-29 23:41:16,812-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
2019-03-29 23:41:16,813-INFO-api_logging.py-api_frame_work-日志信息:开始测试
2019-03-29 23:41:16,813-INFO-api_logging.py-api_frame_work-日志信息:正在运行第4条用例：异常key
2019-03-29 23:41:16,813-INFO-api_logging.py-api_frame_work-日志信息:测试数据是:{'mobilephone': 'aaa', 'pwd': '123456'}
2019-03-29 23:41:16,902-INFO-api_logging.py-api_frame_work-日志信息:测试结果是：<Response [200]>
2019-03-29 23:41:16,903-ERROR-api_logging.py-api_frame_work-日志信息:请求出错了，错误是：'10001' != '20111'
- 10001
+ 20111

2019-03-29 23:41:16,929-INFO-api_logging.py-api_frame_work-日志信息:结束这个测试
